<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <EnableNUnitRunner>true</EnableNUnitRunner>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="NUnit.Framework.Legacy.ClassicAssert" Alias="Assert" />
    <PackageReference Include="Avalonia" Version="$(AvaloniaSampleVersion)" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="$(AvaloniaSampleVersion)" />
    <PackageReference Include="Avalonia.Themes.Simple" Version="$(AvaloniaSampleVersion)" />
    <PackageReference Include="Avalonia.Headless.NUnit" Version="$(AvaloniaSampleVersion)" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
    <PackageReference Include="Moq" Version="4.21.0" />
    <PackageReference Include="NUnit" Version="5.0.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="6.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\AvaloniaEdit.TextMate\AvaloniaEdit.TextMate.csproj" />
    <ProjectReference Include="..\..\src\AvaloniaEdit\AvaloniaEdit.csproj" />
  </ItemGroup>

</Project>
